services:
  - type: web
    name: backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "daphne -b 0.0.0.0 -p ${PORT} backend.asgi:application"
    repo: https://github.com/MederOsmonov08/Backend.git
    branch: main
