services:
  - type: web
    name: backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    repo: https://github.com/Doni23kj/Backend.git
    branch: main
