# Generated by Django 5.2.7 on 2025-10-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_type',
            field=models.CharField(choices=[('direct', 'Прямой чат'), ('group', 'Групповой чат')], default='direct', max_length=10),
        ),
    ]
