# Generated by Django 5.2.7 on 2025-10-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userprofile_avatar_url_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_file',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
